### ISSUE TITLE
Old events page

### ISSUE THREAD

**Issue by jamesdoc** [kingdom-code/kingdom-code#5]
The home page is a good place for the recent events… but not all the events going back to 2015… 

[Example from FeL](https://www.frontendlondon.co.uk/archive)

**Comment by jamesdoc** [comment]
Needs this to completed too: https://github.com/kingdom-code/kingdom-code/issues/1

**Comment by paddybc** [comment]
Work has been started in https://github.com/kingdom-code/kingdom-code/tree/old-event-page.
I will probably not pick up before the end of May, so feel free to take off me.

Basic structure done in event-archive.njk with archive.md and started styling but not complete.

**Comment by jamesdoc** [comment]
> I will probably not pick up before the end of May, so feel free to take off me.

I picked this up. A year and a half later. ✅
