### ISSUE TITLE
Smooth scroll the banner anchor link

### ISSUE THREAD

**Issue by jamesdoc** [kingdom-code/kingdom-code#6]
Rather than jump to the correct part of the page, smooth scroll to the correct area (with as little JS as possible please)

**Comment by jamesdoc** [comment]
[MoveTo](https://github.com/hsnaydd/moveTo) looks handy for this…

**Comment by ariddlestone** [comment]
Do you want me to do this?

**Comment by jamesdoc** [comment]
Thanks @ariddlestone 👍
